theme: jekyll-theme-hacker
title: Kashmir54 
author: Kashmir54

repository: kashmir54/kashmir54_page
collections:
  walkthroughs:
    output: true
  ctfs:
    output: true
  tools:
    output: true
    
defaults:
  - scope:
      path: ""
    values:
      layout: default

#Others
markdown: kramdown

# Syntax highlighting
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    #default_lang: python
    css_class   : 'syntax'